apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zz-frame-test
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nuxt.cdc.internal
      secretName: zz-frame-test-tls
  rules:
    - host: nuxt.cdc.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zz-frame-nodeport-test
                port:
                  number: 80
